version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=youtube
      - POSTGRES_PASSWORD=test91

  web:
    build: .  # Kropka oznacza, że Dockerfile jest w tym samym katalogu co docker-compose.yml
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
